import shutil
import subprocess
from pathlib import Path

import pytest

from ci_workflows.registry import Caller
from ci_workflows.render import (
    RenderError,
    _resolve_includes,
    cron_minute_for_repo,
    render_marker,
    render_template,
)

REPO_ROOT = Path(__file__).parent.parent
TEMPLATES = REPO_ROOT / "templates"
FIXTURES = Path(__file__).parent / "fixtures"


def test_cron_minute_is_stable_for_same_repo():
    assert cron_minute_for_repo("example-org/alpha") == cron_minute_for_repo("example-org/alpha")


def test_cron_minute_in_0_to_59_range():
    for repo in (
        "example-org/a",
        "example-org/b",
        "example-org/example-docs",
        "example-org/example-app",
    ):
        assert 0 <= cron_minute_for_repo(repo) <= 59


def test_cron_minute_distributes_across_callers():
    repos = [f"example-org/r{i}" for i in range(20)]
    minutes = {cron_minute_for_repo(r) for r in repos}
    # Expect > half unique; not a strict guarantee but catches degenerate hashing.
    assert len(minutes) > 10


def test_render_marker_yields_expected_yaml():
    got = render_marker(
        version="v1",
        tier="python-app",
        source_commit="abc1234",
        synced="2026-04-20T14:30:00Z",
        synced_by="sync.py@v1",
    )
    expected = (
        "# Auto-generated by ci-workflows sync — do not edit\n"
        "version: v1\n"
        "tier: python-app\n"
        "source_commit: abc1234\n"
        "synced: 2026-04-20T14:30:00Z\n"
        "synced_by: sync.py@v1\n"
    )
    assert got == expected


def test_render_template_python_app_sweep_v2_substitutes_cron():
    got = render_template(
        template_path=TEMPLATES / "python-app" / "gitleaks-sweep.yml",
        templates_root=TEMPLATES,
        caller_entry=_caller_default(),
        version="v2",
        synced="2026-04-24T12:00:00Z",
        cron_minute=17,
    )
    expected = (FIXTURES / "rendered-python-app-sweep.v2.min17.yml").read_text()
    assert got == expected


def test_render_template_docs_static_ci_v2_matches_fixture():
    got = render_template(
        template_path=TEMPLATES / "docs-static" / "ci.yml",
        templates_root=TEMPLATES,
        caller_entry=_caller_docs_static(),
        version="v2",
        synced="2026-04-24T12:00:00Z",
        cron_minute=None,
    )
    expected = (FIXTURES / "rendered-docs-static-ci.v2.yml").read_text()
    assert got == expected


def test_render_template_docs_static_sweep_v2_substitutes_cron():
    got = render_template(
        template_path=TEMPLATES / "docs-static" / "gitleaks-sweep.yml",
        templates_root=TEMPLATES,
        caller_entry=_caller_docs_static(),
        version="v2",
        synced="2026-04-24T12:00:00Z",
        cron_minute=49,
    )
    expected = (FIXTURES / "rendered-docs-static-sweep.v2.min49.yml").read_text()
    assert got == expected


def test_render_template_python_app_sweep_v2_heavy_matches_fixture():
    """Sweep override → arm64-runner; cron 35 matches sha256(example-heavy)[0] % 60."""
    heavy = Caller(
        repo="example-org/example-heavy",
        tier="python-app",
        pilot=False,
        retry_setup=True,
        runs_on=(
            ("gitleaks-fast", "arm64-runner"),
            ("lint-test", "codeberg-medium"),
            ("sweep", "arm64-runner"),
        ),
    )
    got = render_template(
        template_path=TEMPLATES / "python-app" / "gitleaks-sweep.yml",
        templates_root=TEMPLATES,
        caller_entry=heavy,
        version="v2",
        synced="2026-04-24T12:00:00Z",
        cron_minute=35,
    )
    expected = (FIXTURES / "rendered-python-app-sweep.v2.heavy.min35.yml").read_text()
    assert got == expected


def test_render_template_runs_on_omitted_jobs_use_tier_defaults():
    """Partial override case (post-2026-05-12 tier-defaults):

    When a caller specifies only ONE runs_on entry, omitted jobs fall back
    to TIER_DEFAULTS (not the global codeberg-tiny default any more). For
    python-app this means lint-test + gitleaks-fast both default to arm64-runner.

    Verify that overriding lint-test to codeberg-medium leaves gitleaks-fast
    at the tier-default arm64-runner, NOT the global codeberg-tiny default.
    """
    partial = Caller(
        repo="example-org/partial",
        tier="python-app",
        pilot=False,
        retry_setup=True,
        runs_on=(("lint-test", "codeberg-medium"),),  # only override lint-test
    )
    got = render_template(
        template_path=TEMPLATES / "python-app" / "ci.yml",
        templates_root=TEMPLATES,
        caller_entry=partial,
        version="v2",
        synced="2026-04-24T12:00:00Z",
        cron_minute=None,
    )
    assert "runs-on: codeberg-medium" in got  # lint-test override applied
    assert "runs-on: arm64-runner" in got  # gitleaks-fast falls back to tier-default
    assert "runs-on: codeberg-tiny" not in got  # NOT the global default any more
    assert "{RUNS_ON_" not in got  # all placeholders resolved


def test_render_template_raises_if_cron_placeholder_missing_minute():
    with pytest.raises(RenderError, match="cron_minute"):
        render_template(
            template_path=TEMPLATES / "python-app" / "gitleaks-sweep.yml",
            templates_root=TEMPLATES,
            caller_entry=_caller_default(),
            version="v1",
            synced="2026-04-20T14:30:00Z",
            cron_minute=None,
        )


def test_render_template_raises_if_cron_minute_passed_without_placeholder():
    with pytest.raises(RenderError, match=r"no \{CRON_MINUTE\} placeholder"):
        render_template(
            template_path=TEMPLATES / "python-app" / "ci.yml",
            templates_root=TEMPLATES,
            caller_entry=_caller_default(),
            version="v1",
            synced="2026-04-20T14:30:00Z",
            cron_minute=17,
        )


@pytest.mark.skipif(shutil.which("actionlint") is None, reason="actionlint not installed")
@pytest.mark.parametrize(
    ("template_name", "cron_minute"),
    [
        ("gitleaks-sweep.yml", 17),
        ("ci.yml", None),
    ],
)
def test_rendered_output_passes_actionlint(tmp_path, template_name, cron_minute):
    got = render_template(
        template_path=TEMPLATES / "python-app" / template_name,
        templates_root=TEMPLATES,
        caller_entry=_caller_default(),
        version="v3.0.3",
        synced="2026-04-20T14:30:00Z",
        cron_minute=cron_minute,
    )
    out = tmp_path / "rendered.yml"
    out.write_text(got)
    result = subprocess.run(
        [
            "actionlint",
            "-config-file",
            str(REPO_ROOT / ".github" / "actionlint.yaml"),
            str(out),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def _caller_default() -> Caller:
    return Caller(repo="example-org/example-app", tier="python-app", pilot=True, retry_setup=True)


def _caller_docs_static() -> Caller:
    return Caller(
        repo="example-org/example-svc",
        tier="docs-static",
        pilot=False,
        retry_setup=True,
    )


def test_render_template_passes_caller_entry_through_to_includes(tmp_path):
    tpl = tmp_path / "ci.yml"
    tpl.write_text("name: t\nsteps:\n  - run: echo pre\n  {{include: snippets/hello.yml}}\n")
    (tmp_path / "snippets").mkdir()
    (tmp_path / "snippets" / "hello.yml").write_text("- name: Hello\n  run: echo hi\n")

    got = render_template(
        template_path=tpl,
        templates_root=tmp_path,
        caller_entry=_caller_default(),
        version="v2",
        synced="2026-04-24T00:00:00Z",
        cron_minute=None,
    )
    assert "- name: Hello" in got
    assert "{{include:" not in got


def test_resolve_includes_inlines_setup_uv():
    body = "      {{include: _snippets/setup_uv.yml}}\n"
    out = _resolve_includes(body, TEMPLATES, _caller_default())
    expected = (FIXTURES / "snippets" / "setup_uv_rendered.yml").read_text()
    assert out == expected


def test_resolve_includes_inlines_install_deps_uv():
    body = "      {{include: _snippets/install_deps_uv.yml}}\n"
    out = _resolve_includes(body, TEMPLATES, _caller_default())
    expected = (FIXTURES / "snippets" / "install_deps_uv_rendered.yml").read_text()
    assert out == expected


def test_render_python_app_v3_pilot():
    got = render_template(
        template_path=TEMPLATES / "python-app" / "ci.yml",
        templates_root=TEMPLATES,
        caller_entry=_caller_default(),
        version="v3.0.3",
        synced="2026-04-24T12:00:00Z",
        cron_minute=None,
    )
    expected = (FIXTURES / "python-app" / "ci_v3_example-app.yml").read_text()
    assert got == expected


def test_render_python_app_v3_retry_setup_is_noop():
    """v3 template no longer references retry_setup — both flag values render identically.

    Guards against accidental re-wiring of the flag in a future change.
    """
    caller_retry_true = Caller(repo="example-org/example-app", tier="python-app", pilot=True, retry_setup=True)
    caller_retry_false = Caller(repo="example-org/example-app", tier="python-app", pilot=True, retry_setup=False)
    kwargs = dict(
        template_path=TEMPLATES / "python-app" / "ci.yml",
        templates_root=TEMPLATES,
        version="v3.0.3",
        synced="2026-04-24T12:00:00Z",
        cron_minute=None,
    )
    assert render_template(caller_entry=caller_retry_true, **kwargs) == render_template(
        caller_entry=caller_retry_false, **kwargs
    )


def test_render_python_app_v3_heavy():
    """Override case: lint-test → codeberg-medium, gitleaks-fast → arm64-runner."""
    heavy = Caller(
        repo="example-org/example-heavy",
        tier="python-app",
        pilot=False,
        retry_setup=True,
        runs_on=(
            ("gitleaks-fast", "arm64-runner"),
            ("lint-test", "codeberg-medium"),
            ("sweep", "arm64-runner"),
        ),
    )
    got = render_template(
        template_path=TEMPLATES / "python-app" / "ci.yml",
        templates_root=TEMPLATES,
        caller_entry=heavy,
        version="v3.0.3",
        synced="2026-04-24T12:00:00Z",
        cron_minute=None,
    )
    expected = (FIXTURES / "python-app" / "ci_v3_example-heavy-heavy.yml").read_text()
    assert got == expected
