"""Template rendering: cron-minute hashing, banner/marker substitution."""

import hashlib
import re
from pathlib import Path

from ci_workflows.registry import Caller


class RenderError(ValueError):
    """Raised when a template substitution fails."""


_INCLUDE_RE = re.compile(r"^(?P<indent>[ \t]*)\{\{\s*(?P<kind>include(?:_if)?)\s*:(?P<args>.*?)\}\}\s*$")
_NESTED_INCLUDE_RE = re.compile(r"\{\{\s*include(?:_if)?\s*:")
# {RUNS_ON_<JOB>} placeholder — <JOB> is uppercase, hyphens converted to underscores.
# E.g. lint-test → {RUNS_ON_LINT_TEST}; gitleaks-fast → {RUNS_ON_GITLEAKS_FAST}.
_RUNS_ON_RE = re.compile(r"\{RUNS_ON_([A-Z_]+)\}")

KNOWN_CONDITIONAL_FLAGS = frozenset({"retry_setup"})


def cron_minute_for_repo(repo: str) -> int:
    """Stable, deterministic 0-59 minute for a repo short name.

    Uses sha256 for stability across Python versions (built-in hash() salt varies).
    """
    short = repo.rsplit("/", 1)[-1]
    digest = hashlib.sha256(short.encode("utf-8")).digest()
    return digest[0] % 60


def render_marker(
    *,
    version: str,
    tier: str,
    source_commit: str,
    synced: str,
    synced_by: str,
) -> str:
    return (
        "# Auto-generated by ci-workflows sync — do not edit\n"
        f"version: {version}\n"
        f"tier: {tier}\n"
        f"source_commit: {source_commit}\n"
        f"synced: {synced}\n"
        f"synced_by: {synced_by}\n"
    )


def render_template(
    *,
    template_path: Path,
    templates_root: Path,
    caller_entry: Caller,
    version: str,
    synced: str,
    cron_minute: int | None,
) -> str:
    body = template_path.read_text()
    body = _resolve_includes(body, templates_root, caller_entry)
    has_cron_placeholder = "{CRON_MINUTE}" in body
    if has_cron_placeholder and cron_minute is None:
        raise RenderError(f"{template_path.name} contains {{CRON_MINUTE}} but cron_minute=None was passed")
    if not has_cron_placeholder and cron_minute is not None:
        raise RenderError(
            f"{template_path.name} has no {{CRON_MINUTE}} placeholder but cron_minute={cron_minute} was passed"
        )
    out = _substitute_runs_on(body, caller_entry)
    out = out.replace("{VERSION}", version).replace("{SYNCED}", synced)
    if cron_minute is not None:
        out = out.replace("{CRON_MINUTE}", str(cron_minute))
    return out


def _substitute_runs_on(body: str, caller: Caller) -> str:
    """Replace {RUNS_ON_<JOB>} placeholders with the caller's per-job runner label.

    <JOB> is uppercased with hyphens → underscores; e.g. {RUNS_ON_LINT_TEST}
    looks up `lint-test` in caller.runs_on, defaulting to "codeberg-tiny".
    """

    def repl(m: re.Match[str]) -> str:
        job = m.group(1).lower().replace("_", "-")
        return caller.runs_on_for(job)

    return _RUNS_ON_RE.sub(repl, body)


def _resolve_includes(body: str, templates_root: Path, caller_entry: Caller) -> str:
    """Expand {{include: path}} and {{include_if: flag, path}} directives inline.

    - Unconditional: always expanded.
    - Conditional: expanded only if `caller_entry.<flag>` is True; otherwise the
      directive line is deleted entirely (no blank-line artifact).
    - Parameterized snippets: {{STEP_NAME}} / {{STEP_COMMAND}} in the snippet body
      are substituted from KEY=value args in the directive.
    - Every line of an inlined snippet is prefixed with the directive line's
      leading whitespace so YAML indentation stays correct under `steps:`.
    - Nested includes (snippet containing `{{include...`) raise RenderError.
    - Missing snippet files raise RenderError.
    - Unknown conditional flag names raise RenderError (typo guard).

    Runs BEFORE {VERSION}/{SYNCED}/{CRON_MINUTE} token substitution so the inlined
    content picks up those tokens in the same pass.
    """
    out_lines: list[str] = []
    for line in body.splitlines(keepends=False):
        m = _INCLUDE_RE.match(line)
        if not m:
            out_lines.append(line)
            continue

        indent = m.group("indent")
        kind = m.group("kind")
        args = m.group("args").strip()

        relpath, params = _parse_include_args(args, kind)

        if kind == "include_if":
            flag_name, relpath = _split_flag_and_relpath(args)
            if flag_name not in KNOWN_CONDITIONAL_FLAGS:
                raise RenderError(
                    f"unknown conditional flag {flag_name!r} in {line!r}; "
                    f"known flags: {sorted(KNOWN_CONDITIONAL_FLAGS)}"
                )
            _, params = _parse_include_args(args, kind)
            else_path = params.pop("else", None)
            if not getattr(caller_entry, flag_name):
                if else_path is None:
                    continue  # drop directive line entirely
                relpath = else_path

        snippet_path = templates_root / relpath
        if not snippet_path.is_file():
            raise RenderError(f"snippet not found: {snippet_path}")
        snippet = snippet_path.read_text()

        if _NESTED_INCLUDE_RE.search(snippet):
            raise RenderError(f"nested include in {relpath} — snippets may not contain include directives")

        for key, value in params.items():
            snippet = snippet.replace("{{" + key + "}}", value)

        for snippet_line in snippet.splitlines():
            out_lines.append(indent + snippet_line if snippet_line else snippet_line)

    result = "\n".join(out_lines)
    if body.endswith("\n"):
        result += "\n"
    return result


def _parse_include_args(args: str, kind: str) -> tuple[str, dict[str, str]]:
    """Parse 'path' or 'path, KEY=val, KEY2=val2' (include) — or
    'flag, path[, KEY=val...]' (include_if).

    Returns (relpath, params_dict). For include_if, the flag is stripped here so
    this function returns only (path, params); caller extracts flag separately
    via _split_flag_and_relpath.
    """
    parts = [p.strip() for p in args.split(",")]
    if kind == "include_if":
        if len(parts) < 2:
            raise RenderError(f"include_if requires 'flag, path': got {args!r}")
        relpath = parts[1]
        param_parts = parts[2:]
    else:
        relpath = parts[0]
        param_parts = parts[1:]
    params: dict[str, str] = {}
    for kv in param_parts:
        if not kv:
            continue
        if "=" not in kv:
            raise RenderError(f"bad include param (missing =): {kv!r}")
        k, _, v = kv.partition("=")
        v = v.strip()
        if v.startswith('"') and v.endswith('"') and len(v) >= 2:
            v = v[1:-1]
        params[k.strip()] = v
    return relpath, params


def _split_flag_and_relpath(args: str) -> tuple[str, str]:
    parts = [p.strip() for p in args.split(",")]
    if len(parts) < 2:
        raise RenderError(f"include_if requires 'flag, path': got {args!r}")
    return parts[0], parts[1]
